CREATE DATABASE TABLE INSERT FROM PRIMARY FOREIGN KEY REFERENCES ON WHERE INNER JOIN
VARCHAR INT NOT NULL TEXT ON DELETE DEFAULT IF EXISTS SET UPDATE CASCADE EXTENSION 

CREATE DATABASE find_restaurant;
